import { firebaseConfig } from './firebase-config.js';
import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js';
import { getAuth, GoogleAuthProvider, signInWithPopup, signOut, onAuthStateChanged, setPersistence, browserLocalPersistence } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js';
import { getFirestore, doc, setDoc, getDoc, collection, getDocs, query, where, writeBatch, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js';
import { getStorage, ref, uploadBytes, getDownloadURL } from 'https://www.gstatic.com/firebasejs/12.2.1/firebase-storage.js';
const B=window.FuelLogBridge;
const app=initializeApp(firebaseConfig), auth=getAuth(app), db=getFirestore(app), storage=getStorage(app);setPersistence(auth,browserLocalPersistence).catch(()=>{});
let user=null, tab='family';
const tripsKey=()=>`fuel-trips-${B.currentVehicleId}`; const getTrips=()=>JSON.parse(localStorage.getItem(tripsKey())||'[]'); const saveTrips=x=>localStorage.setItem(tripsKey(),JSON.stringify(x));
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function ensureUI(){if(document.querySelector('#familyFab'))return;document.body.insertAdjacentHTML('beforeend',`<button id="familyFab" title="Family & Pro">👥</button><div id="familyOverlay" class="fl-overlay"><section class="fl-sheet"><header class="fl-head"><div><h2>Family & Pro</h2><div class="fl-muted">แชร์รถ · ทริป · รูปและ Cloud</div></div><button class="fl-close" id="familyClose">×</button></header><div class="fl-tabs"><button data-ftab="family">ครอบครัว</button><button data-ftab="trip">ทริป</button><button data-ftab="cloud">Cloud</button></div><div id="familyBody"></div></section></div>`);document.querySelector('#familyFab').onclick=open;document.querySelector('#familyClose').onclick=close;document.querySelector('#familyOverlay').onclick=e=>{if(e.target.id==='familyOverlay')close()};document.querySelectorAll('[data-ftab]').forEach(b=>b.onclick=()=>{tab=b.dataset.ftab;render()})}
function open(){document.querySelector('#familyOverlay').classList.add('open');render()}function close(){document.querySelector('#familyOverlay').classList.remove('open')}
function activeBtn(){document.querySelectorAll('[data-ftab]').forEach(x=>x.classList.toggle('active',x.dataset.ftab===tab))}
function car(){return B.vehicles.find(v=>v.id===B.currentVehicleId)||{name:'รถ'} }
function familyView(){const v=car();return `<div class="fl-grid"><div class="fl-card full"><div class="fl-login">${user?`<div class="fl-user"><img src="${esc(user.photoURL||'')}" referrerpolicy="no-referrer"><div><b>${esc(user.displayName||user.email)}</b><div class="fl-muted">${esc(user.email)}</div></div></div><button class="fl-btn" id="flSignOut">ออกจากระบบ</button>`:`<div><b>เข้าสู่ระบบ Google</b><div class="fl-muted">เพื่อแชร์รถกับคนในบ้าน</div></div><button class="fl-btn primary" id="flLogin">เข้าสู่ระบบ</button>`}</div></div><div class="fl-card"><h3>รถที่เลือก</h3><div class="fl-kpi">${esc(v.name)}</div><div class="fl-muted">รหัสในเครื่อง ${esc(v.id)}</div></div><div class="fl-card"><h3>สถานะ Cloud</h3><div id="cloudState" class="fl-kpi">—</div><div class="fl-muted">ตรวจสมาชิกและสิทธิ์</div></div><div class="fl-card full"><h3>สร้างรหัสเชิญ</h3><div class="fl-row"><input id="inviteEmail" class="fl-input" type="email" placeholder="Gmail สมาชิก"><select id="inviteRole" class="fl-input"><option value="editor">Editor</option><option value="viewer">Viewer</option></select><button id="makeInvite" class="fl-btn primary">สร้าง</button></div><div id="inviteResult" class="fl-muted" style="margin-top:8px"></div></div><div class="fl-card full"><h3>เข้าร่วมด้วยรหัส</h3><div class="fl-row"><input id="joinCode" class="fl-input" maxlength="8" placeholder="รหัสเชิญ 8 ตัว"><button id="joinInvite" class="fl-btn primary">เข้าร่วม</button></div></div></div>`}
function tripView(){const ts=getTrips().sort((a,b)=>String(b.date).localeCompare(String(a.date)));const total=ts.reduce((s,x)=>s+(+x.fuel||0)+(+x.toll||0)+(+x.parking||0)+(+x.food||0)+(+x.other||0),0);return `<div class="fl-grid"><div class="fl-card"><h3>จำนวนทริป</h3><div class="fl-kpi">${ts.length}</div></div><div class="fl-card"><h3>ต้นทุนรวม</h3><div class="fl-kpi">฿${total.toLocaleString('th-TH')}</div></div><div class="fl-card full"><h3>เพิ่มทริป/หน้างาน</h3><div class="fl-grid"><input id="tName" class="fl-input" placeholder="ชื่องาน/ปลายทาง"><input id="tDate" class="fl-input" type="date" value="${new Date().toISOString().slice(0,10)}"><input id="tFuel" class="fl-input" type="number" placeholder="ค่าน้ำมัน"><input id="tToll" class="fl-input" type="number" placeholder="ค่าทางด่วน"><input id="tParking" class="fl-input" type="number" placeholder="ค่าจอด"><input id="tFood" class="fl-input" type="number" placeholder="ค่าอาหาร/ที่พัก"><input id="tOther" class="fl-input" type="number" placeholder="อื่น ๆ"><button id="saveTrip" class="fl-btn primary">บันทึกทริป</button></div></div><div class="fl-card full"><h3>ประวัติทริป</h3><div class="fl-list">${ts.length?ts.map(x=>`<div class="fl-item"><div><b>${esc(x.name)}</b><div class="fl-muted">${esc(x.date)} · ${esc(x.note||'')}</div></div><div><b>฿${((+x.fuel||0)+(+x.toll||0)+(+x.parking||0)+(+x.food||0)+(+x.other||0)).toLocaleString('th-TH')}</b><button class="fl-close" data-deltrip="${x.id}" style="font-size:16px">×</button></div></div>`).join(''):'<div class="fl-muted">ยังไม่มีทริป</div>'}</div></div></div>`}
function cloudView(){return `<div class="fl-grid"><div class="fl-card full"><h3>ซิงก์รถที่เลือก</h3><p class="fl-muted">อัปโหลดรายการเติมน้ำมัน ค่าใช้จ่าย รอบบำรุง และทริปของรถนี้ขึ้น Firestore โดยไม่ลบข้อมูลในเครื่อง</p><div class="fl-row"><button id="pushCloud" class="fl-btn primary">อัปโหลดขึ้น Cloud</button><button id="pullCloud" class="fl-btn">ดึงจาก Cloud</button></div><div id="syncMsg" class="fl-muted" style="margin-top:8px"></div></div><div class="fl-card full"><h3>อัปโหลดรูปส่วนตัว</h3><div class="fl-row"><select id="photoType" class="fl-input"><option value="receipt">ใบเสร็จ</option><option value="odometer">เรือนไมล์</option><option value="maintenance">งานซ่อม</option><option value="documents">เอกสารรถ</option></select><input id="cloudPhoto" class="fl-input" type="file" accept="image/*,application/pdf"><button id="uploadPhoto" class="fl-btn primary">อัปโหลด</button></div><div id="photoMsg" class="fl-muted" style="margin-top:8px"></div></div><div class="fl-card full"><h3>OCR</h3><p class="fl-muted">ฟังก์ชันสแกนบิลเดิมของ v3.7 ยังอยู่ครบ ใช้จากหน้าบันทึกเติมน้ำมันได้ และรูปที่ยืนยันแล้วอัปโหลดเข้าพื้นที่สมาชิกของรถได้จากหน้านี้</p></div></div>`}
function render(){activeBtn();const body=document.querySelector('#familyBody');body.innerHTML=tab==='family'?familyView():tab==='trip'?tripView():cloudView();bindView();if(tab==='family'&&user)checkCloud()}
function bindView(){document.querySelector('#flLogin')?.addEventListener('click',()=>signInWithPopup(auth,new GoogleAuthProvider()).catch(e=>alert(e.message)));document.querySelector('#flSignOut')?.addEventListener('click',()=>signOut(auth));document.querySelector('#saveTrip')?.addEventListener('click',()=>{const name=document.querySelector('#tName').value.trim();if(!name)return alert('กรุณาใส่ชื่อทริป');const t={id:'trip-'+Date.now(),vehicleId:B.currentVehicleId,name,date:document.querySelector('#tDate').value,fuel:+document.querySelector('#tFuel').value||0,toll:+document.querySelector('#tToll').value||0,parking:+document.querySelector('#tParking').value||0,food:+document.querySelector('#tFood').value||0,other:+document.querySelector('#tOther').value||0,createdBy:user?.uid||'local'};const a=getTrips();a.push(t);saveTrips(a);render()});document.querySelectorAll('[data-deltrip]').forEach(b=>b.onclick=()=>{saveTrips(getTrips().filter(x=>x.id!==b.dataset.deltrip));render()});document.querySelector('#makeInvite')?.addEventListener('click',makeInvite);document.querySelector('#joinInvite')?.addEventListener('click',joinInvite);document.querySelector('#pushCloud')?.addEventListener('click',pushCloud);document.querySelector('#pullCloud')?.addEventListener('click',pullCloud);document.querySelector('#uploadPhoto')?.addEventListener('click',uploadPhoto)}
async function ensureUser(){if(!user)throw new Error('กรุณาเข้าสู่ระบบ Google ก่อน');await setDoc(doc(db,'users',user.uid),{email:user.email,emailLower:user.email.toLowerCase(),displayName:user.displayName||'',photoURL:user.photoURL||'',updatedAt:serverTimestamp()},{merge:true})}
async function vehicleDoc(){return doc(db,'vehicles',B.currentVehicleId)}
async function checkCloud(){try{const s=await getDoc(await vehicleDoc());document.querySelector('#cloudState').textContent=s.exists()?(s.data().members?.[user.uid]?.role||'สมาชิก'):'ยังไม่ขึ้น Cloud'}catch{document.querySelector('#cloudState').textContent='ตรวจไม่ได้'}}
async function makeInvite(){try{await ensureUser();const email=document.querySelector('#inviteEmail').value.trim().toLowerCase(),role=document.querySelector('#inviteRole').value;if(!email)throw Error('ใส่ Gmail สมาชิก');const vd=await vehicleDoc(),snap=await getDoc(vd);if(!snap.exists())await setDoc(vd,{name:car().name,ownerUid:user.uid,members:{[user.uid]:{role:'owner',email:user.email}},createdAt:serverTimestamp()});else if(snap.data().ownerUid!==user.uid)throw Error('เฉพาะ Owner สร้างรหัสเชิญได้');const code=Math.random().toString(36).slice(2,10).toUpperCase();await setDoc(doc(db,'invites',code),{vehicleId:B.currentVehicleId,vehicleName:car().name,emailLower:email,role,ownerUid:user.uid,expiresAt:Date.now()+7*864e5,createdAt:serverTimestamp()});document.querySelector('#inviteResult').innerHTML=`รหัสเชิญ: <b style="font-size:18px">${code}</b> · อายุ 7 วัน`}catch(e){alert(e.message)}}
async function joinInvite(){try{await ensureUser();const code=document.querySelector('#joinCode').value.trim().toUpperCase(),ir=doc(db,'invites',code),is=await getDoc(ir);if(!is.exists())throw Error('ไม่พบรหัสเชิญ');const inv=is.data();if(inv.expiresAt<Date.now())throw Error('รหัสหมดอายุ');if(inv.emailLower&&inv.emailLower!==user.email.toLowerCase())throw Error('รหัสนี้สร้างไว้สำหรับ Gmail อื่น');const vd=doc(db,'vehicles',inv.vehicleId),vs=await getDoc(vd);if(!vs.exists())throw Error('ไม่พบรถ');const data=vs.data(),members={...(data.members||{}),[user.uid]:{role:inv.role,email:user.email,displayName:user.displayName||''}};await setDoc(vd,{members,lastJoinCode:code},{merge:true});let v=B.vehicles.find(x=>x.id===inv.vehicleId);if(!v){B.vehicles.push({id:inv.vehicleId,name:inv.vehicleName||data.name||'รถที่แชร์'});B.persistAll();B.refresh()}alert('เข้าร่วมรถสำเร็จ')}catch(e){alert(e.message)}}
async function pushCloud(){const m=document.querySelector('#syncMsg');try{await ensureUser();const vd=await vehicleDoc(),vs=await getDoc(vd);if(!vs.exists())await setDoc(vd,{name:car().name,ownerUid:user.uid,members:{[user.uid]:{role:'owner',email:user.email}},createdAt:serverTimestamp()});const batch=writeBatch(db);for(const [col,arr] of [['entries',B.entries.filter(x=>x.vehicleId===B.currentVehicleId)],['costs',B.costs.filter(x=>x.vehicleId===B.currentVehicleId)],['reminders',B.reminders.filter(x=>x.vehicleId===B.currentVehicleId)],['trips',getTrips()]])for(const x of arr)batch.set(doc(db,'vehicles',B.currentVehicleId,col,x.id),{...x,updatedBy:user.uid,updatedAt:serverTimestamp()},{merge:true});await batch.commit();m.textContent='อัปโหลดสำเร็จ'}catch(e){m.textContent=e.message}}
async function pullCloud(){const m=document.querySelector('#syncMsg');try{await ensureUser();for(const [col,target] of [['entries',B.entries],['costs',B.costs],['reminders',B.reminders]]){const ss=await getDocs(collection(db,'vehicles',B.currentVehicleId,col));const ids=new Set(target.map(x=>x.id));ss.forEach(d=>{const x=d.data();if(!ids.has(x.id))target.push(x)});}const ts=await getDocs(collection(db,'vehicles',B.currentVehicleId,'trips'));saveTrips(ts.docs.map(d=>d.data()));B.persistAll();B.refresh();m.textContent='ดึงข้อมูลสำเร็จ'}catch(e){m.textContent=e.message}}
async function uploadPhoto(){const msg=document.querySelector('#photoMsg');try{await ensureUser();const f=document.querySelector('#cloudPhoto').files[0];if(!f)throw Error('เลือกไฟล์ก่อน');const type=document.querySelector('#photoType').value,path=`vehicles/${B.currentVehicleId}/${type}/${Date.now()}-${f.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`,r=ref(storage,path);await uploadBytes(r,f,{contentType:f.type,customMetadata:{uploadedBy:user.uid}});const url=await getDownloadURL(r);await setDoc(doc(db,'vehicles',B.currentVehicleId,'photos',String(Date.now())),{type,path,url,name:f.name,uploadedBy:user.uid,createdAt:serverTimestamp()});msg.innerHTML=`อัปโหลดสำเร็จ · <a href="${url}" target="_blank" rel="noopener" style="color:#54d4ae">เปิดไฟล์</a>`}catch(e){msg.textContent=e.message}}
onAuthStateChanged(auth,async u=>{user=u;if(u)await ensureUser().catch(()=>{});if(document.querySelector('#familyOverlay')?.classList.contains('open'))render()});ensureUI();
